---
- name: main config
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    gitfqdn: gmail.com
  tasks:
    - include: basics.yml
    - include: gendev.yml
    - include: feddev.yml
    - include: gitconfig.yml
    - include: srccode.yml
